### ISSUE TITLE
Projects in the west directory are not forbidden

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#102]
Originally reported by @tejlmand.

For example, even with forbidding projects named ~`west`~ `.west` or `manifest`, this manifest fragment is legal:

```
  projects:
    - name: not-west
      path: .west
```

This creates a structure where the top-level `west` directory contains a `.git` for the `not-west` repository, which is very strange.

Arguably this is user error but the current behavior seems undesirable. We should consider what to do here:

- warn
- error
- skip the project?
- ...

**Comment by mbolivar** [comment]
> And in future we could consider to add `--force` to `west` to allow user to overrule whatever restriction `west` poses

This would require adding `--force` to basically every invocation of west that touches a project or parses a manifest.

Perhaps a `manifest` configuration option?

**Comment by tejlmand** [comment]
@mbolivar you're right, it would be required for every command, expect maybe `west list` ;)

I think my main point was to suggest the error for now, and then take it up, if someone needs this.

**Comment by mbolivar** [comment]
Erroring out seems sane.

**Comment by mbolivar** [comment]
Migrating to enhancement

**Comment by marc-hb** [comment]
Since this issue was filed, WEST_DIR has been renamed to hidden directory `.west` by commit 045b591e17b1bcab and has changed A LOT in nature.

BUT I tested this again with `path: .west/foo` and west version 1.3 still did not mind. So this issue is still valid.

**Comment by marc-hb** [comment]
Fix submitted by @pdgendt in
- #754
