### ISSUE TITLE
Run a binary onto a board, d'oh

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/west#112]
I'm using whatever west is being run with "make flash" in today's Zephyr master. So, when I run:

> PYTHONPATH=/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/scripts/meta /usr/bin/python3 /home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/scripts/meta/west/main.py flash --skip-rebuild --help

I get (among other output):

> Flash and run a binary onto a board.

I don't know what "run a binary onto a board" means. That makes me concerned that I'd better flash and run it myself, I only need west to tell me how (likely will be subject of the other ticket).

**Comment by mbolivar** [comment]
Thanks for noticing the typo. I've sent a fix.

**Comment by mbolivar** [comment]
Hi @pfalcon, I hope you'll forgive the piggybacking, but I've tacked another patch onto

**Comment by mbolivar** [comment]
Sorry for the close/reopen, I pressed the "close and comment" button by mistake.
