### ISSUE TITLE
git: specifying revision to checkout / fetch fails

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/west#139]
Creating a manifest with a specific SHA revision may fail, with an error that it is not advertized by server:

Example snippet:
```
  projects:
    - name: zephyr
      revision: aa35e2df3693c9f797508314abd405940edf1c09
```

Error experienced with `west fetch` (after `west init -m <repo>`)
```
...
Receiving objects: 100% (243333/243333), 128.35 MiB | 9.72 MiB/s, done.
Resolving deltas: 100% (175926/175926), done.
error: Server does not allow request for unadvertised object aa35e2df3693c9f797508314abd405940edf1c09
FATAL ERROR: Command 'git fetch --tags -- https://github.com/zephyrproject-rtos/zephyr aa35e2df3693c9f797508314abd405940edf1c09' failed for zephyr (zephyr/)
```

but the reference is valid, as can be seen be checking out manually:
```
$ cd zephyr/
$ git remote add origin https://github.com/zephyrproject-rtos/zephyr
$ cd zephyr/
$ git fetch origin
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (4/4), done.
...
$ git checkout aa35e2df3693c9f797508314abd405940edf1c09
Checking out files: 100% (9693/9693), done.
Note: checking out 'aa35e2df3693c9f797508314abd405940edf1c09'.
```

**Comment by mbolivar** [comment]
Is the object in the history of some branch?

**Comment by tejlmand** [comment]
seems that revision is gone (I could have been on a branch).
This revision is on master `bfad2a0cbfee37708e6641f4f740df292d4fd2b7` but it should happen to any valid revision.

**Comment by marc-hb** [comment]
> error: Server does not allow request for unadvertised object aa35e2df3693c9f797

This is a security feature (and an FAQ). Allowing direct SHA1 access can:
- open access to objects deleted but not garbage collected yet
- circumvent refs based permissions like the ones Gerrit and maybe others use.

`allowAnySHA1InWant`

> seems that revision is gone (I could have been on a branch).

Or not: afraid it's too expensive to check.
