### ISSUE TITLE
Create a command line interface for dealing with manifests

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#166]
We need a way to deal with the west manifest from the command line. At the very least, this needs to cover creating a "frozen" or "pinned" manifest file which nails down the revisions of west and every project.

The interface would look like this:

```
west manifest <operation> [operation-arguments]
```

The `<operation>` argument would be a mutually exclusive group of options, to at least include `--freeze`.

So you could write:

```
west manifest --freeze [more --freeze-specific options]
```

(Using `--` style options in a mutually exclusive group instead of yet another subparser makes the argparse configuration easier to deal with.)

If we had another hypothetical operation `--foo`, you could write:

```
west manifest --foo [more --foo-specific options]
```

But this would be an error, since `--freeze` and `--foo` are mutually exclusive:

```
west manifest --freeze --foo
```

**Comment by tejlmand** [comment]
Sounds good to me.
For the start, just the `--freeze` in order to keep things simple.

So, do you expect to overwrite existing `west.yml` with the frozen one, to make it easy for user to commit and push, or allow him to specify an out file, for the frozen manifest ?

**Comment by carlescufi** [comment]
Agreed, can we perhaps reuse some of the code in here: https://github.com/zephyrproject-rtos/west/pull/136 ?

**Comment by mbolivar** [comment]
> So, do you expect to overwrite existing `west.yml` with the frozen one, to make it easy for user to commit and push, or allow him to specify an out file, for the frozen manifest ?

I was just going to print it to stdout, with an `-o FILENAME` option to set the output file.

```
west manifest --freeze -o my_saved_manifest.yml
```

**Comment by carlescufi** [comment]
>I was just going to print it to stdout, with an -o FILENAME option to set the output file.

That is also what I implemented, I think that is a logical first step. We can of course later add a new `-r, --replace` option that actually replaces it

**Comment by mbolivar** [comment]
:+1: or `-i` / `--in-place[=SUFFIX]` mirroring sed's ability to make a backup
