### ISSUE TITLE
First 'west update' fails, second succeeds

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#173]
This affects 'west update' and 'west selfupdate' equally, of course.

Steps to reproduce:

```
$ cd $(west list -f="{abspath}" west)
$ git fetch upstream
$ git checkout upstream/master~3
$ west selfupdate
=== Updated west (.west/west/) to master (from https://github.com/zephyrproject-rtos/west).
/home/mbolivar/.local/share/virtualenvs/west/bin/python3: can't open file 'selfupdate': [Errno 2] No such file or directory
$ west selfupdate
```

The second one succeeds.

**Comment by tejlmand** [comment]
Observation: when using `--reset-west` the selfupdate works on first try.
```
$ west selfupdate --reset-west
=== Fetching and resetting west (.west/west/) to 'master'
From https://github.com/zephyrproject-rtos/west
 * branch            master     -> FETCH_HEAD
```

**Comment by mbolivar** [comment]
@tejlmand should we close this, or keep it open until we get one more upstream west commit merged so we can test it starting from c5323934df286aaa2e3d400dba417b838bfa9d19?

**Comment by tejlmand** [comment]
You already closed it :p 
Think it's fine to close, cause you can still test it, by checking out an older revision, and then apply this fix manually without committing, and then run `west selfupdate`

**Comment by mbolivar** [comment]
Sorry, stupid combo buttons ;). OK, let's keep this closed, thanks.
