### ISSUE TITLE
west selfupdate does not respect new west remote

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#179]
To reproduce, change west remote URL in the manifest repository (e.g. change from upstream to a personal fork) and run `west selfupdate`.

I expect this to update my west installation's remote URL (e.g. change to my personal fork), but it does not. For example, `git remote -v` is the same before and after.

Note that running `west -vv selfupdate` shows the correct remote (e.g. my fork) is being fetched from. So this is not a correctness issue for the command, just a minor issue with the remotes.

**Comment by tejlmand** [comment]
This is not only applicable to `west` remote, but goes for all remotes in the manifest file.
So if changing current behavior, I believe this issue should then be extended to cover manifest projects as well.

There were some discussion on this on slack (unfortunately I can't go so far back).
I remember there were mixed opinions about handling of remotes.
Especially whether `west` should update remotes or not.

Some were strongly against `west` modifying their remotes.
As example, if new remotes are added / deleted, then `west` cannot know, if user had added a git remote manually. In which case, the user probably don't want that remote to be modified by `west`

Personally, I believe we should keep as-is, or decide to remove `west` configured remotes.
The remotes are not used by `west` anyway, and managing them using `west` has a risk of colliding with user controlled remotes.
