### ISSUE TITLE
source ~/.zephyrrc automatically when using west

### ISSUE THREAD

**Issue by alexanderwachter** [zephyrproject-rtos/west#180]
It would be useful if west checks for .zephyrrc file in the homedir and source it if present.

**Comment by alexanderwachter** [comment]
my zephyrrc looks as following:
export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
export GNUARMEMB_TOOLCHAIN_PATH=/usr/
because i'm not using the zephyr toolchain.

A configuration option that tells west what toolchain to use would be even better.
Maybe it could even ask for the toolchain when doing the west init command

**Comment by tejlmand** [comment]
@alexanderwachter as discussed here:
https://github.com/zephyrproject-rtos/west/issues/198
https://github.com/zephyrproject-rtos/west/issues/175

The idea is to be able to specify this in west config files in future, and then add the posibility of letting  `CMake` fetch those settings.

This will further allow for global setting, while at same time allow for project local overwrites.
#215 is step one in this process.

**Comment by mbolivar** [comment]
I'm going to close this for now since the ultimately proposed feature (west configuration options for the toolchain) is something we'd like to do for 'west build' in the zephyr repository.
