### ISSUE TITLE
west fails to init repo across disks in windows

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/west#186]
When running `west init` on a disk different that the disk having the temp directory, west fails as:

Error
```
=== Creating repository for nrf (nrf\)
Traceback (most recent call last):
  File "c:\python37\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\<user>\\AppData\\Local\\Temp\\manifest_p54lzomp' -> 'E:\\ncs2\\nrf'
```

**Comment by mbolivar** [comment]
Dang.

Maybe we need to use .west/tmp as a staging directory during init. If we pass that to mkdtemp in the dir kwarg, we can guarantee the temporary directory is inside the installation.
