### ISSUE TITLE
Allow specifying source folder without -s in west build

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/west#203]
This is actually implemented in the zephyr repository but I'd rather keep the west issues here.

Today one needs to build with:

`west build -b reel_board -s samples/hello_world`

I think that it would make sense to be able to use `ArgParse`'s positional arguments to be able to do:

`west build -b reel_board samples/hello_world`

**Comment by mbolivar** [comment]
We can't do this, because we already accept arbitrary arguments to pass on to cmake with `nargs="*"`. Passing a source directory as a `nargs='?'` positional would be ambiguous.

**Comment by mbolivar** [comment]
(For the record, I agree it would make sense and wish we could do that too)
