### ISSUE TITLE
West manifest imports

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#221]
This issue has evolved over time following a lot of discussion. Its eventual scope settled down to an enhancement to west which allows users to import content from other manifest files into their west.yml.

The final "resolved" manifest contains its own projects, plus projects obtained via imports. This resolved manifest is the logical data which commands like `west list`, `west update`, etc. operate on.

Imports can come from:

- within the manifest repository itself (if I want to split up my manifest into multiple files in one repository)
- a project in my manifest file's `projects:` list (if e.g. I want my own manifest which treats the zephyr repository as a project, and import zephyr/west.yml into my own manifest to get its modules)
- a combination of these

Imports are recursive: I can import manifest A, which itself imports B, and get the projects from B.

The Zephyr [documentation PR 20433](https://github.com/zephyrproject-rtos/zephyr/pull/20433) is the authoritative definition of the scope of this issue (i.e. of west #221).

Definition of done:

- [x] add initial support in west https://github.com/zephyrproject-rtos/west/pull/330/
- [x] documentation for initial support level https://github.com/zephyrproject-rtos/zephyr/pull/20433
- [x] cut a beta release (note: done as 0.6.99.dev4)
- [x] collect user feedback
- [x] implement 'map' imports (planned feature not provided initially)
- [x] update documentation to reflect 'map' import final implementation
- [x] do another beta (note: done as 0.6.99.dev5)
- [x] west.manifest unit tests for all major use cases (see https://github.com/zephyrproject-rtos/west/pull/363)
- [x] integration tests for built-in west commands for all major use cases (see https://github.com/zephyrproject-rtos/west/pull/363)
- [x] collect final user feedback

Specific items to address in follow up work:

- [x] west manifest --resolve implementation (https://github.com/zephyrproject-rtos/west/pull/348)
- [x] whether we can load files from the file system when importing from projects, e.g. https://github.com/zephyrproject-rtos/west/pull/330#issuecomment-566982785 (answer: [no](https://github.com/zephyrproject-rtos/west/issues/221#issuecomment-567401732))
- [x] double-processing some projects in west update https://github.com/zephyrproject-rtos/west/pull/330#pullrequestreview-333329703 (addressed in https://github.com/zephyrproject-rtos/west/pull/364)
- [x] whether we can bring back the existing remote behavior on clone now that we have ignore semantics https://github.com/zephyrproject-rtos/west/pull/330#discussion_r359373681 (addressed in https://github.com/zephyrproject-rtos/west/pull/364)
- [x] allow west update on projects in the top level manifest even when it uses imports https://github.com/zephyrproject-rtos/west/pull/330#issuecomment-566982042 (addressed in https://github.com/zephyrproject-rtos/west/pull/364)
- [x] detect and throw errors on manifest import loops (addressed in https://github.com/zephyrproject-rtos/west/pull/366)

**Comment by mbolivar** [comment]
Note also that this idea basically mandates introducing additional manifest file sections if we want to support features like Repo's `<default sync-j="4"/>` in west: we can't assume we can configure non-project west behavior in our `manifest: defaults: ...` anymore, as the `manifest: defaults:` section would be restricted to project attributes only.

**Comment by tejlmand** [comment]
Thanks for raising this :)

A couple of comments for some clarification:
For project attributes, you state that last manifets wins.
> Project-specific attributes (such as clone-depth and path) would take their values from the last manifest file in the argument list which set them. E.g. a clone-depth set in MANIFEST2 would override any value in MANIFEST1.

but for the defaults, it is first manifest.
> The merged manifest file would take its default values from the first defaults: section which defines them. 

Why that difference ? And isn't there a risk associated with this, that users might find it hard to understand when a given setting is taken from first manifest or final manifest ?

Another question, a manifest may have
```
self:
    path: zephyr
```
but that is optional. So when combining multiple manifest files into a single, what will happen with `self` sections ?
Will they become independent projects ?
What will their `url` be ?
What if `self` is missing ?

**Comment by tejlmand** [comment]
> Note also that this idea basically mandates introducing additional manifest file sections if we want to support features like Repo's <default sync-j="4"/>

Why does this need to go into the manifest ?
With #215 we could allow users the ability to specify: `west config --global sync-j 4` and then use the information in `west` when syncing projects

**Comment by mbolivar** [comment]
Thanks for feedback!

> Why that difference ?

I tried to explain the rationale in the original issue description:

"This is done as a heuristic to minimize the length of the generated manifest, because it's likely that upstream defaults will apply to the most projects once we split zephyr/ext into individual repositories. It doesn't affect the actual values that apply to each project."

In other words, I expect that manifests which appear later in the list will have fewer projects, so my thought was to keep the length of the merged manifest shorter by taking defaults from the first project. That will make those defaults apply to the most projects possible.

E.g. I expect mainline to look something like this once we split ext/ up:

```
  projects:
    - name: net-tools
      revision: 30b7efa827b04d2e47840716b0372737fe7d6c92
    - name: ext1
      revision: abc
    - name: ext2
      revision: abc
    # ...
    - name: ext23
      revision: abc
    - name: mcuboot
      revision: abc
    - name: ci-tools
      revision: abc
    # ...
```

That's already more than 25 projects and can only increase as mainline zephyr gains more integrations, which can all be specified as a simple name/revision pair for now since they take a default remote.

(The number 23 in `ext23` is from how many sub-directories are inside `ext/*`, which is the appropriate level because it splits up per-vendor HALs and other projects from different sources into their own repositories.)

By contrast, the downstream repositories will probably have fewer than 10 projects.

So if the merged manifest takes defaults from the second, downstream manifest, all the `remote:` attributes in the 25 upstream projects have to be inlined. If it takes it from the first, upstream manifest, only 10 projects need 3 lines in the manifest to specify. So the resulting merged manifest is shorter if the first manifest's defaults win.

I'm not married to the idea though and if we decide there are good reasons that taking the last defaults is better even though the merged manifest will be longer, that's OK too. I think there are valid reasons on either side.

> And isn't there a risk associated with this, that users might find it hard to understand when a given setting is taken from first manifest or final manifest ?

I don't think so. The final manifest is self-contained and the defaults will be clearly specified at the top.

> Why does this need to go into the manifest ?
> With #215 we could allow users the ability to specify: west config --global sync-j 4 and then use the information in west when syncing projects

You're totally right. I forget repo doesn't have a separate config file system. This is definitely the way to go, +1 great idea.

**Comment by tejlmand** [comment]
@mbolivar Thank you for the clarification and the example.

> The final manifest is self-contained and the defaults will be clearly specified at the top.

Which of course helps a lot as it is clear what the end result is.
I see the reason for keeping the final manifest as short as possible.

I assume this functionality is mostly targeted for automatic merging of file, e.g. for CI.

**Comment by mbolivar** [comment]
I've begun work on this. It's going to be a release blocker for west 0.7.

**Comment by tejlmand** [comment]
> whether we can load files from the file system when importing from projects, e.g. #330 (comment)

This is nice to have, far from need to have, so I suggest to keep out of `0.7`scope and maybe create a followup task so it can be addressed individually later :wink:
