### ISSUE TITLE
How to use cmake to generate ELF file with relative paths?

### ISSUE THREAD

**Issue by overheat** [zephyrproject-rtos/west#228]
Hi,
I wonder to know if possible to use west to generate ELF file with relative paths.
The situation is that I work on the windows, I suppose most FW engineer does, and compile zephyr on the WSL. Therefore I cannot debug the ELF file on windows, which my Jlink debugger connect, because the path inside ELF is not relative paths.

"CMAKE_USE_RELATIVE_PATHS" inside cmake already has no effect in cmake 3.13, do you have other solution?

Thanks!

**Comment by mbolivar** [comment]
Hi @overheat -- can you reopen this as a Zephyr issue? This is a build system issue, not a west issue.

CC: @SebastianBoe
