### ISSUE TITLE
`west info` command

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/west#233]
Having a `west info` command available may be useful in order to expose several informations about the `west` installation an the project installled.

Those info can also be used by build build systems or CI,

Such information that can be useful:
- west topdir
- board listing

Dedicated information can be retrieved in similar way as `west list` using format, example:
`west info --format={topdir}`

Feel free to add suggestions in comments

**Comment by mbolivar** [comment]
At first thought, I would prefer to have separate commands for the items listed in the issue description. We can hide them by default (porcelain and plumbing) if they're too noisy for the `west -h` output.

**Comment by tejlmand** [comment]
not sure on separate commands.
Cause the more commands of such style we create, the higher the risk that at some point, a new _info_ command is added that collides with a potential downstream extension command.

Which make me actually consider, should a `west info` output be allowed to fetch info from extension command ? 
so that if a project contains a `west info` as extension, then the output from that command can be concatenated with built-in `west info`

**Comment by mbolivar** [comment]
This needs to be teased apart into what's core west versus what's an extension command. Removing good first issue label because of that.

**Comment by mbolivar** [comment]
Closing. `west topdir` is now implemented, and a separate zephyr issue for board info is https://github.com/zephyrproject-rtos/zephyr/issues/19760
