### ISSUE TITLE
Add support for Make as a CMake generator

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/west#252]
Currently the code uses `DEFAULT_CMAKE_GENERATOR = Ninja`. Add a command-line switch and a configuration option to use Make instead.

**Comment by mbolivar** [comment]
does `-- -G'Unix Makefiles'` not work?

**Comment by carlescufi** [comment]
@mbolivar it works indeed, but it's a bit cumbersome. I wonder if we could give special treatment to the generator and add a `-g/--generator` with shortened names:

```
-g ninja
-g make
```

**Comment by carlescufi** [comment]
In addition to a `-g` command-line option, I suggest we add a config option:

```
[build]
generator = ninja/make/...
```

**Comment by galak** [comment]
We should at least have a way of setting the preference in the config file.

**Comment by mbolivar** [comment]
A `build.generator` config option seems fine to me. I'm -1 on wrapping cmake with west options unnecessarily though. That way leads madness.

**Comment by mbolivar** [comment]
> generator = ninja/make/...

We should use the actual generator names supported by CMake and pass them unmodified (so 'Unix Makefiles', 'Ninja', etc.). Let cmake do the validation for us, etc.
