### ISSUE TITLE
Add a command-line option for verbose Makefiles

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/west#253]
Add a command-line switch that adds `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` to the CMake invocation.

**Comment by mbolivar** [comment]
`-- -DCMAKE_VERBOSE_MAKEFILE=YES`

**Comment by carlescufi** [comment]
@mbolivar I would suggest we automatically add that option when using `-vv` so that:

- `-v` shows the cmake/ninja command
- `-vv` shows the actual commands executed by ninja

**Comment by mbolivar** [comment]
Doing so would force a CMake re-run, which may not be what users want.

**Comment by mbolivar** [comment]
Is adding the CMake variable setting to the command line really so bad? Can we close this?

**Comment by galak** [comment]
> Is adding the CMake variable setting to the command line really so bad? Can we close this?

So while not exactly related to this, I feel like having this feature allows one to replicate the following usage model:

```
$ cmake -DBOARD=frdm_k64f ..
$ make VERBOSE=1
```

**Comment by mbolivar** [comment]
> So while not exactly related to this, I feel like having this feature allows one to replicate the following usage model:

OK, so how about the ability to pass additional options to the build tool?

```
west build --build-opt "VERBOSE=1" -- -G'Unix Makefiles'
```

**Comment by galak** [comment]
I'm good with adding a --build-opt and just having the other passed to through to cmake directly.  Might be nice to add something in the west docs about `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`

**Comment by mbolivar** [comment]
> I'm good with adding a --build-opt and just having the other passed to through to cmake directly. Might be nice to add something in the west docs about -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

I will do both things in https://github.com/zephyrproject-rtos/zephyr/pull/15801 before dropping the DNM.
