### ISSUE TITLE
Show the CMake and Ninja/make command-line strings

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/west#254]
When building with -v, show the actual commands for cmake and ninja.

**Comment by mbolivar** [comment]
already done, you just need `-vv`:

https://github.com/zephyrproject-rtos/west/blob/master/src/west/cmake.py#L33

 feel free to lower the level of verbosity

**Comment by galak** [comment]
>already done, you just need `-vv`: ...

@mbolivar 

Would be nice if we could be consistent here.  Right now for ‘flash’ only a single ‘-v’ is needed to see the command.

**Comment by carlescufi** [comment]
@galak I have a PR that fixes this.

**Comment by carlescufi** [comment]
@galak I have a PR that fixes this.

**Comment by mbolivar** [comment]
> Would be nice if we could be consistent here. Right now for ‘flash’ only a single ‘-v’ is needed to see the command.

Makes sense to me, will wait for PR from @carlescufi
