### ISSUE TITLE
Dryrun support

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/west#256]
Have the ability to do a dry run to see what commands would get invoked without actual doing them

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by carlescufi** [comment]
@galak do you want this for all commands or just for `west build`?

**Comment by galak** [comment]
all commands.

**Comment by mbolivar** [comment]
Not possible. For example, some flash commands depend on the output of previously executed commands; it's not as simple as a build system DAG.

**Comment by mbolivar** [comment]
What commands are most important?

**Comment by galak** [comment]
> What commands are most important?

Cmake and flashing commands to start with

**Comment by mbolivar** [comment]
> Cmake and flashing commands to start with

I already said that flashing is not possible :)
