### ISSUE TITLE
flash option to erase not working.

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/west#276]
I'm sure I'm doing something wrong.

```
lilith[191]$ west --version
West bootstrapper version: v0.5.8 (/home/pab/.local/lib/python3.6/site-packages/west/_bootstrap)
West repository version: v0.5.8-8-gc23549f (/mnt/devel/external/zp/.west/west)
lilith[192]$ west flash -d xenon --flash-opt -e chip
ninja: no work to do.
Using runner: pyocd
usage: pyocd [-h] [--dt-flash {Y,y,N,n,yes,no,YES,NO}] --target TARGET
             [--daparg DAPARG] [--pyocd PYOCD] [--flash-opt FLASH_OPT]
             [--frequency FREQUENCY] [--gdb-port GDB_PORT] [--tui]
             [--board-id BOARD_ID]
pyocd: error: argument --flash-opt: expected one argument
lilith[193]$ west flash -d xenon --flash-opt -echip
ninja: no work to do.
Using runner: pyocd
usage: pyocd [-h] [--dt-flash {Y,y,N,n,yes,no,YES,NO}] --target TARGET
             [--daparg DAPARG] [--pyocd PYOCD] [--flash-opt FLASH_OPT]
             [--frequency FREQUENCY] [--gdb-port GDB_PORT] [--tui]
             [--board-id BOARD_ID]
pyocd: error: argument --flash-opt: expected one argument
lilith[194]$ west flash -d xenon --flash-opt '-e chip'
ninja: no work to do.
Using runner: pyocd
Flashing Target Device
usage: pyocd flash [-h] [-j PATH] [--config PATH] [--no-config]
                   [--script PATH] [-O OPTION=VALUE] [-da DAPARG [DAPARG ...]]
                   [--pack PATH] [-v] [-q] [-u UNIQUE_ID] [-b BOARD]
                   [-t TARGET] [-f FREQUENCY] [-W] [-e {auto,chip,sector}]
                   [-a ADDR] [--trust-crc] [--format {bin,hex,elf}]
                   [--skip BYTES]
                   PATH
pyocd flash: error: argument -e/--erase: invalid choice: ' chip' (choose from 'auto', 'chip', 'sector')
ERROR: command exited with status 2: pyocd flash -e sector -t nrf52840 '-e chip' /mnt/devel/zapps/mesh_sp/xenon/zephyr/zephyr.hex
run as "west -v flash -d xenon --flash-opt '-e chip'" for a stack trace
```

**Comment by mbolivar** [comment]
```
--flash-opt -e chip
```

The shell is parsing `-e` as the value given to `--flash-opt`, and `chip` as a separate positional. Try quoting:

```
--flash-opt "-e chip"
```

**Comment by pabigot** [comment]
That's the last example but using `'-e chip'` instead of `"-e chip"` , I think.

**Comment by mbolivar** [comment]
Ah, sorry, I missed that there were multiple examples. I don't have a pyocd board on me right now but will get one later today to figure this out.

**Comment by pabigot** [comment]
You don't need one; it fails before it gets to touching the hardware.

**Comment by mbolivar** [comment]
```
west flash -d build/hello_world/particle_xenon/ --flash-opt "-e=chip"
```

This gets as far as failing with no debug probes for me -- but since I don't have a board, I'm not sure it's actually chip erasing.

**Comment by mbolivar** [comment]
I'm sorry, wrong copy/paste.

```
west flash -d build/hello_world/particle_xenon/ --flash-opt=-e=chip
```

**Comment by mbolivar** [comment]
An option to avoid the argparse-specific usage of `=` would be to split the `--flash-opt` argument before shelling out. Right now, it's passed in its entirety as a single argv option to the underlying pyocd call.

**Comment by pabigot** [comment]
Thanks; that works.  I'll leave to you whether it's a bug that merits code changes; I wouldn't have thought of replacing spaces with `=`.

**Comment by mbolivar** [comment]
> Thanks; that works. I'll leave to you whether it's a bug that merits code changes; I wouldn't have thought of replacing spaces with `=`.

At the very least we need to fix the help string. Let's start there and not do any splitting to keep backwards compatibility. I want to generalize the option and make it available to more runner backends, so we can deal with behavioral changes at that time.
