### ISSUE TITLE
Allow to specify repository name

### ISSUE THREAD

**Issue by vanwinkeljan** [zephyrproject-rtos/west#283]
It would be nice that there is an attribute to specify the repository name (eg. `repo-name`) that together with the `remote` can be combined into a URL to clone from.
This would allow to use the same repo for multiple projects, eg. in the case of multiple API version, without sacrificing the benefits of the remote concept.

See also: https://github.com/zephyrproject-rtos/zephyr/pull/17714#discussion_r307496625

**Comment by mbolivar** [comment]
Thinking about it, that's reasonable and shouldn't be too hard to implement. I'm giving it a go now.

**Comment by mbolivar** [comment]
@vanwinkeljan I've implemented this feature as `repo-path`, to make it clearer that it can contain slashes and is not just a name. Please see #284 -- any testing or feedback is welcome.
