### ISSUE TITLE
west update is not verbose enough by default

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/west#380]
I am labeling this as a bug because it has already caused confusion among our users.

The following 2 cases should warn the user by default, with an option to disable the warning:

- `west update` with a project in the manifest's SHA, but with uncommitted changes, This should warn the user by default so that the user **is informed** that west update did not bring the "revision" to the one specified in the manifest. Many users make changes to the projects while testing, and then forget about them but really meant to undo them, and they are simply not aware right now.

- `west update` with a committed SHA (but detached HEAD) that is a descendant of the manifest's SHA. Here a user might have forgotten to create a branch, but has committed a change to the repo. Unless the user knows how to use `git reflog` it will "lose" the commit it created. Incidentally, `--keep-descendants` does not work in this case, and west reverts back to the manifest SHA.

Alternatively we can add a `west reset --hard` command. I think we need this anyway at some point so that stale folders are removed from the workspace.

CC @koffes

**Comment by mbolivar** [comment]
A fix is in #382.
