### ISSUE TITLE
Error happens when west init/update on windows

### ISSUE THREAD

**Issue by wentongwu** [zephyrproject-rtos/west#395]
Error: no west.main in C:\Desktop\zephyr\code\.west\west

**Comment by wentongwu** [comment]
can anyone mark the priority of this issue as high, I'm blocking by it.

**Comment by wentongwu** [comment]
@mbolivar-nordic

**Comment by mbolivar-nordic** [comment]
West has been tested on windows. I'm confident there's an issue in your local Python environment. Please try uninstalling and reinstalling. If you continue to have problems please add steps to reproduce.

**Comment by mbolivar-nordic** [comment]
Didn't mean to close, sorry, just meant to comment. I'll leave this open for now, but as I said, west is used every day on Windows by many people.

**Comment by wentongwu** [comment]
@mbolivar-nordic thanks, it works well on my side after uninstalling and reinstalling west.
