### ISSUE TITLE
usage with gerrit repos

### ISSUE THREAD

**Issue by wusj** [zephyrproject-rtos/west#403]
The URL of a gerrit repo is like this:
ssh://user1@hostname/foo
ssh://user2@hostname/foo
A unique repo has the different URL for different user, how to set project's url in west.yml?

**Comment by mbolivar-nordic** [comment]
Hello and thanks for your question.

> The URL of a gerrit repo is like this:
> ssh://user1@hostname/foo

This is a git over SSH URL. It is not specific to gerrit:

https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols

([GitHub also supports SSH URLs](https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh), except the user is always "git".)

Android uses Gerrit extensively, however, it uses Gerrit over HTTP instead in the default public AOSP repo manifest:

https://android.googlesource.com/a/platform/manifest/+/refs/heads/master/default.xml

Therefore, what I understand from your question is that each person cloning your manifest has a unique username and password on your server, which is using Gerrit to serve Git over SSH.

What I would suggest is to just use something like ssh://hostname/foo in the west URLs, and have each user configure the SSH client to pass the user and password. There is a stackoverflow on this here:

https://stackoverflow.com/a/10056098

I hope that one of the solutions there answers your question. If not, please see the Git book page https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage and the manual page https://git-scm.com/docs/gitcredentials.

Please reopen if you continue to have issues. Thanks again.
