### ISSUE TITLE
How to using West to checkout a revision of Zephyr 

### ISSUE THREAD

**Issue by nqduy35** [zephyrproject-rtos/west#451]
Hello, I follow the tutorial of zephyr and download zephyr's newest version. I want to checkout to the tag zephyr-v2.3.0. 
I've read the tutorial of West, but I don't find how to do it. Did I miss something? Do you have any suggestions?

**Comment by nqduy35** [comment]
I found the solution: West hasn't supported to it yet but we can use git inside the zephyr folder. 
Suppose that we are in zephyrproject's directory
$ cd zephyr
$ git checkout <VERSION>

**Comment by mbolivar-nordic** [comment]
> West hasn't supported to it yet but we can use Git inside the zephyr folder.

Hi, this is by design. West does not change the manifest repository contents. The user is responsible for doing this using git.
