### ISSUE TITLE
west update command need update west.yaml first.

### ISSUE THREAD

**Issue by Cherish-forever** [zephyrproject-rtos/west#455]
Hi
I am using west for my project. Sometimes I need add some repository or delete some repository in west.yaml file.
and my partner need git pull west.ymal  repository first, then west update for each project. 
So I think git pull west.yaml first, then update project from west.yaml

**Comment by mbolivar-nordic** [comment]
Hi, thanks for the idea, but `west update` by design does not change the contents of the manifest repository in any way. It says this directly in the `west help update` output:

```
This command does not alter the manifest repository's contents.
```

It is the user's responsibility to manage the manifest repository using git.
