### ISSUE TITLE
New release with narrow update feature

### ISSUE THREAD

**Issue by temap** [zephyrproject-rtos/west#501]
HI, could you tell me when the new version will be released with the narrow update feature? 
We need a narrow update for west tool because we have ~30 minutes clones which is annoying.

Thanks

**Comment by marc-hb** [comment]
I don't know the answer but I never experienced any problem running the latest commit:
```shell
pip3 uninstall west
git clone https://github.com/zephyrproject-rtos/west
cd west
pip3 install -e .
```
"Don't do this at home!" :-)

**Comment by temap** [comment]
@marc-hb, thanks for the solution, but I would like to have it on the official release. Could you explain about release cycles. When to expect a new west version?

**Comment by mbolivar-nordic** [comment]
Hi. I'm starting the release process tomorrow. It usually only takes a day or so. I therefore expect it no late than sometime early next week.

**Comment by temap** [comment]
@mbolivar-nordic thank you
