### ISSUE TITLE
qemu_x86 not building (unrecognized command-line option '-m32'; did you mean '-mbe32')

### ISSUE THREAD

**Issue by maksimdrachov** [zephyrproject-rtos/west#538]
Hi,

I'm trying to replicate [this](https://docs.zephyrproject.org/2.3.0/boards/x86/qemu_x86/doc/index.html).

However when I try to build, I'm getting an error:

```
arm-none-eabi-gcc: error: unrecognized command-line option '-m32'; did you mean '-mbe32'?
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /Users/maksim/zephyrproject/zephyr/samples/synchronization/build
```

The entire output:
![Capture d’écran 2021-09-13 à 15 46 14](https://user-images.githubusercontent.com/39975120/133095055-f6c1bc98-2d02-4a06-9c2c-3c9faf7c43a5.png)

I've tried to do `west update` and pulled the last commit from zephyr, this didn't help.

Environment:
- MacOS
- west

**Comment by maksimdrachov** [comment]
After looking into this a bit more, I realise this is probably because the toolchain I'm using only supports ARM.

So then the question is, how to compile qemu on MacOS?

**Comment by marc-hb** [comment]
@maksimdrachov this really does not like a west question. Try `west -v ...` then run directly without west the same `cmake` command that west runs and you should see the exact same error.

Try https://github.com/zephyrproject-rtos/zephyr/discussions or even better the new Discord channels.
