### ISSUE TITLE
Support cloning to topdir

### ISSUE THREAD

**Issue by il-steffen** [zephyrproject-rtos/west#569]
I like west to clone one of the project repos to ".", so that I can place the most prominent launch/entry scripts in the topdir. 

I've tried setting "self/path: ." but it fails moving the cloned repo from manifest-tmp to ".":
https://github.com/zephyrproject-rtos/west/blob/main/src/west/app/project.py#L305

If I fix that manually, everything seems to work. Are there any other expected complications?

I guess if someone were to import such a manifest, they would have to override the path for this project. Same as with other name collisions?

**Comment by mbolivar-nordic** [comment]
> I like west to clone one of the project repos to ".", so that I can place the most prominent launch/entry scripts in the topdir.

Thank you for the request, but this is not possible as a design decision.
