### ISSUE TITLE
west init from a private repository

### ISSUE THREAD

**Issue by Machine-Hum** [zephyrproject-rtos/west#589]
Hey,

I've [forked this](https://github.com/zephyrproject-rtos/example-application) project and have moved it into a private repository. I'm now trying to clone it and am experiencing issues with credentials.

```
[machinehum@whitebox ~]$ --mr main id01_trackpad_fw
bash: --mr: command not found
[machinehum@whitebox ~]$ west init -m https://github.com/Machine-Hum/id01_trackpad_fw --mr main id01_trackpad_fw
=== Initializing in /home/machinehum/id01_trackpad_fw
--- Cloning manifest repository from https://github.com/Machine-Hum/id01_trackpad_fw, rev. main
Cloning into '/home/machinehum/id01_trackpad_fw/.west/manifest-tmp'...
Username for 'https://github.com': machine-hum
Password for 'https://machine-hum@github.com': 
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/Machine-Hum/id01_trackpad_fw/'
FATAL ERROR: command exited with status 128: git clone --branch main https://github.com/Machine-Hum/id01_trackpad_fw /home/machinehum/id01_trackpad_fw/.west/manifest-tmp
```
A normal git clone works fine, as I've set up my keypairs and whatnot. Is there a way to get the same effect as west init -m by using a git clone?

**Comment by marc-hb** [comment]
west does not know anything about git authentication.

Run `west -vv init -m https://github.com/Machine-Hum/id01_trackpad_fw --mr main id01_trackpad_fw`. This will fail but it will print a `git clone ...` command. Try to run that git clone command.

**Comment by Machine-Hum** [comment]
I got the answer, when cloning you can't use the https://github.com - this tells git to use normal passwords. The command needs to be ` west init -m git@github.com

**Comment by marc-hb** [comment]
> you can't use the https://github.com/ - this tells git to use normal passwords

`.netrc` tokens work too, not just passwords `https://` only tells git to use... https://, the rest is up to libcurl and github, git does not know about it.

> git@github.com

For git this syntax means ssh (and then git still does not about authentication).
