### ISSUE TITLE
West update returns error when submanifests directory does not exist

### ISSUE THREAD

**Issue by aborisovich** [zephyrproject-rtos/west#594]
According to documentation on [Manifest Import Details](https://docs.zephyrproject.org/latest/develop/west/manifest.html#manifest-import-details)

> Import keys are optional. If any of import-1, ..., import-N are missing, west will not import additional manifest data from that project.

As far as my understanding goes this behavior also works when `import` statement is inside `self`  statement.
Like so:
![image](https://user-images.githubusercontent.com/12482515/181787398-f7d58812-df73-4f9f-bcee-a8b0aa62235e.png)

However, `west update` command raises following error when **submanifests** directory does not exist:
![image](https://user-images.githubusercontent.com/12482515/181787816-6948b651-48ec-489b-85ce-f409b1dc8429.png)

On the other hand, `west update` command does not rise any error when directory exists but does not have any files.

### Reproduction steps
1. In <enter_your_project_path> create west.yml manifest with following content:
![image](https://user-images.githubusercontent.com/12482515/181788586-f3cf23ae-3a4f-4453-b67f-95a0211197a5.png)

2. Execute command `west init -l <enter_your_project_path>`
3. Execute command `west update`

### Actual result
`west update` command results in error (ignore my setup paths):
![image](https://user-images.githubusercontent.com/12482515/181788973-cd1fffc0-7c68-43b4-b47a-7c42800d6b96.png)

### Expected result
Command `west update` performs update of found projects.

### Work-around
In your <enter_your_project_path> create empty (or with some junk files) directory _submanifests_.

**Comment by marc-hb** [comment]
Good catch

git has an "interesting" design where it does not track directories. git only creates directories "lazily" only when it has to create files in them.

As you mentioned the workaround is to git add `submanifests/.empty_placeholder`. Adding them to git makes sure no one experiences the issue.

**Comment by mbolivar-nordic** [comment]
>> Import keys are optional. If any of import-1, ..., import-N are missing, west will not import additional manifest data from that project.

> As far as my understanding goes this behavior also works when import statement is inside self statement.

Yes, and this is explicitly spelled out in the same documentation:

> If self-import is missing, no additional files in the manifest repository (beyond the top-level file) are imported.

However, "missing" is not about the *file* being missing on the file system. It's about the *key* being missing in the YAML file.

> Like so:
> image

So this example is not related to the documentation. If you wrote:

```yaml
manifest:
  # ...
  self:
    # no import here!
```

Then the above documentation would apply. But since the `import: submanifests` value is present in your example, west goes to look for it, and reports an error when it fails to find it. This is expected behavior. I hope this clears this up.
