### ISSUE TITLE
feature: Highlight modified files

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/west#606]
When performing a `west update` the output is nicely formatted, e.g.:
```
=== updating hal_nordic (modules/hal/nordic):
M	nrfx/mdk/system_nrf5340_application.c
HEAD is now at a4458a1 include: add "zephyr/" include prefix
```
Could we add by default/as a user option to highlight modified files in yellow? When updating, we get almost 100 lines of prints, and it is easy to miss modified files.

**Comment by mbolivar-nordic** [comment]
@koffes the output you are referring to is indeed from git, not west.

And in particular it means that you have locally modified files.

There is already a command which can look through your workspace and just print output for local modifications, and doesn't print any output for projects which have clean trees: `west status`.

I'm going to close this as already implemented. Please reopen with more details if I didn't get your point.
