### ISSUE TITLE
Add shell completion for fish shell

### ISSUE THREAD

**Issue by jeppenodgaard** [zephyrproject-rtos/west#607]
Currently the following shells are supported:
- bash
- zsh

The fish auto completion documentation:
https://fishshell.com/docs/current/completions.html

**Comment by mbolivar-nordic** [comment]
Patches are welcome. No plans to work on this.

**Comment by carlescufi** [comment]
@jeppenodgaard thanks for creating the issue! I will try to find time to work on this, although I myself am a zsh user.
