### ISSUE TITLE
Issue in west flash when multiple boards are connected 

### ISSUE THREAD

**Issue by harshvsingh-eaton** [zephyrproject-rtos/west#612]
Tried flashing the code using west flash when two different boards are connected 

Hardware connected : STM32F429ZI and STM32F767ZI 

Steps to reproduce : 
1. Connect both the boards in two different com ports.
2. Compiled the code using west build  -b nucleo_f429zi ./ -p for stm32 nucleo board and tried flashing the generated hex using 
 1. west flash 
 2. west flash -r openocd --serial 0667FF525750877267023015 (This uses the unique id obtained by pyocd list command ) but in both the cases the flash is not successful . It appears the west is  not able to identify the correct hardware even if the unique id is provided

Kindly let me know if any approach available to flash the code when two different boards are connected and we want to flash the code in one out of the two.

**Comment by mbolivar-nordic** [comment]
Please run `west -v flash` in the failing and working scenarios and see if anything is wrong with the commands west is running.

Have you tried using `--dev-id`?

**Comment by harshvsingh-eaton** [comment]
This command worked for me : > west flash -r openocd --cmd-pre-init  "hla_serial 0667FF525750877267023015"

Thank you .
