### ISSUE TITLE
West update can leave manifest and west in unusable states

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#62]
As a user, I expect that if `west update` fails (either run directly or as implied by `west fetch` or `pull`), that my installation is still in a usable state. However, the current implementation can leave either of these repositories in a broken (half-rebased) state if the update fails, with git merge conflict markers in source files.

To reproduce, just commit any changes that won't rebase cleanly and run west update.

The behavior instead should be to see if the rebase is possible to complete cleanly *without* damaging the existing installation, reporting an error if it fails with additional information on how to proceed.

**Comment by ulfalizer** [comment]
Think some variant of https://github.com/zephyrproject-rtos/west/pull/81#discussion_r226635054 would solve it in a nicer and simpler way.
