### ISSUE TITLE
"west build" exits with code 0 when interrupted with Ctrl-C (SIGINT)

### ISSUE THREAD

**Issue by xudongzheng** [zephyrproject-rtos/west#636]
If "west build" is used as part of a larger script, it can be helpful to distinguish between a complete build versus an interrupted build.

```
$ west --version
West version: v1.0.0
$ python3 --version
Python 3.8.9
```

**Comment by mbolivar-nordic** [comment]
This is a valid issue, but it will require some changes to west's internals and a new release to fix.

**Comment by marc-hb** [comment]
This was just discussed in
- #633 

Maybe also in much older:
- #135

**Comment by mbolivar-nordic** [comment]
Fix is posted: https://github.com/zephyrproject-rtos/west/pull/639

**Comment by mbolivar-nordic** [comment]
@xudongzheng could you please test the latest main branch fixes your issue?

**Comment by mbolivar-nordic** [comment]
Thank you for testing! I will make a new west release soon.
