### ISSUE TITLE
`already defined as extension command`-error prints wrong spec

### ISSUE THREAD

**Issue by M1cha** [zephyrproject-rtos/west#675]
Apparently it always prints the last spec ever processed instead of the one that actually caused the error.
The errors seem to be logged after the fact via `self.queued_io.append`, maybe there's some weird python lambda scoping going on?

**Comment by marc-hb** [comment]
Can you please share some reproduction steps? Unfortunately this repo does not have any bug template but https://github.com/zephyrproject-rtos/zephyr/tree/main/.github/ISSUE_TEMPLATE has a good checklist if you need one. Thanks!
