### ISSUE TITLE
Create new project with help of west

### ISSUE THREAD

**Issue by sathishscripts** [zephyrproject-rtos/west#70]
It would be great if west can be used to create new project. Basically it creates directory with initial template for starting new project. 

Just like django-admin startproject mysite.

**Comment by mbolivar** [comment]
I think I'm going to close this:

1. This is a zephyr-specific issue, so it should be opened against the zephyr repository as an enhancement request for a west extension command (e.g. "add `west app` extension to create a new application")
2. I think that implementing it would require that every time someone adds a new feature to how Zephyr applications are managed, the extension be kept up to date. That is, in my opinion, an intractable cat herding problem, so we shouldn't try to support it.

Please feel free to open a new issue in the zephyr repository if you think this is still valid, @sathishscripts.
