### ISSUE TITLE
fatal: fetch-pack: invalid index-pack output

### ISSUE THREAD

**Issue by kenkit** [zephyrproject-rtos/west#709]
![image](https://github.com/zephyrproject-rtos/west/assets/1732471/027995e3-ef78-41a6-905b-09938eb65bd6)

**Comment by kenkit** [comment]
I've tried changing git configs even switching networks. 
But that is the error I get, is there a way to manually clone the repo.

**Comment by marc-hb** [comment]
When happens when you use git directly? Try:
```
git clone https://github.com/zephyrproject-rtos/zephyr
```

PS: avoid screenshots when possible, use copy/paste instead: https://docs.zephyrproject.org/latest/develop/getting_started/index.html#use-copy-paste

**Comment by kenkit** [comment]
Or you can make it possible to only clone upto x depth so as to avoid this issue

**Comment by marc-hb** [comment]
I have no idea what the issue was.

**Comment by kenkit** [comment]
I guess being able to use repo not initialized by west as I seemed to be having an issue cloning.

**Comment by marc-hb** [comment]
`west` is "only" a git user just like you and me. Anything `west` does with git, you can do it without `west` too. Even after `west` has (successfully!) used git, you can still use most git commands in repos cloned by `west`, `west` is not exclusive/"jealous".

But if you have issues cloning then it's not going to work for you and it's not going to work for `west`, there's no difference and no magic there. Git must work, period.

How much time did you spend looking at https://docs.zephyrproject.org/latest/develop/west/index.html so far?
