### ISSUE TITLE
How to deinit a west project ? 

### ISSUE THREAD

**Issue by 1d0ntknow** [zephyrproject-rtos/west#749]
I accedentially executed west init under c:\ directly and I don't know which folders were added

**Comment by pdgendt** [comment]
`west list` shows you all the project's folders, besides that you need to remove the `.west` folder.

**Comment by marc-hb** [comment]
> besides that you need to remove the .west folder.

I think there was some reluctance to make this method "official" and documented but in practice it works reliably 100% of the time.

**Comment by marc-hb** [comment]
Next time please use Discord for a usage question like this, there is a #west channel. https://github.com/zephyrproject-rtos/zephyr/discussions is another option.
