### ISSUE TITLE
West should support reinitializing an existing installation

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#77]
We've always left a hole in west's `init_reinit()` routine, which is what gets run when a user attempts to `west init` an existing west installation. Right now, it simply reports an error.

With the new configuration file infrastructure (https://github.com/zephyrproject-rtos/west/pull/75), we should have all the pieces to reinitialize now:

1. west repository
2. manifest repository
3. configuration directory with new west and manifest revisions
4. west marker file

Once those are reinitialized, the next `west fetch` should pull down the updated configuration specified by the above without any extra work or changes.

**Comment by ulfalizer** [comment]
Looked into the `west reset` thing, but it's starting to feel icky to me. I don't think we should create our own less general Git command wrappers in cases where you could easily just use `west forall ...`.

On the upside, `git reset --keep` is even better than I expected it to be (see the docstring below). If reiniting must reset stuff, then I think it's the best choice.

Icky WIP below, which I don't think we should go for. I was thinking of only supporting the mode flags (`--soft`, `--hard`, etc.), but once you start duplicating existing flags like that just to pass them through as-is, it's starting to stink, IMO.

```python
class Reset(WestCommand):
    def __init__(self):
        super().__init__(
            'reset',
            _wrap('''
            Reset projects to '{}'.

            Runs 'git reset --keep {0}' for the specified projects (default:
            all projects), resetting them back to the revision specified in the
            manifest (as of the most recent fetch of project data).

            'git reset --keep' works like 'git reset --hard', but aborts the
            reset if any file modified between HEAD and '{0}' has local
            changes, carrying over any local changes otherwise.

            Extra arguments are passed as-is to 'git reset', and override
            '--keep {0}'. For example, 'west reset --soft HEAD~' runs 'git
            reset --soft HEAD~' in all projects.
            '''.format(_MANIFEST_REV_BRANCH)),
            accepts_unknown_args=True)

    def do_add_parser(self, parser_adder):
        return _add_parser(parser_adder, self, _project_list_arg)

    def do_run(self, args, user_args):
        for project in _all_projects(args):
            _git(project, 'reset',
                 extra_args=user_args or ('--keep', _MANIFEST_REV_BRANCH))
```
